### ISSUE TITLE
Not updating document with a blank line under a structure section

### ISSUE THREAD

**Issue by Lawouach** [atomist/yaml-updater#1]
I have a circle file that I try to edit by adding a new webhook url. Here is the yaml file:

```
notify:

  webhooks:
  - url: https://somedomain.com
```

I'm parsing that document with js-yaml safeLoad function and then update the webhooks list as follows:

```
notify.webhooks.push({ url: "https://ka.boom"});
const newYml = updateYamlDocument({ notify }, myYml);
```

Interestingly, this doesn't update the document actually. The reason is because of that blank line between `notify` and `webhooks`. When I remove that blank line, that works fine.

I can only assume that the blank line tells the js processor that webhooks is not under notify but its own top-level section. So the document is likely valid (structuraly) but not in the way we expect. Altough, having said that, the code doesn't choke on pushing a new url:

```
console.log(JSON.stringify(notify));
# {"webhooks":[{"url":"https://somedomain.com"},{"url":"https://webhook.atomist.com/circle"}]}
```

Is this a bug in the yaml file itself or is it an issue with the updateYamlDocument function?

**Comment by ddgenome** [comment]
I'm pretty sure the current updater does not handle this correctly.

**Comment by ddgenome** [comment]
I have failing tests for this and I think the issue is with un-indenting the value of the object being updated.
